(defmacro define (name &rest body)
  (if (atom name)
      `(setq ,name ,@body)
    `(defun ,(car name) ,(cdr name)
       ,@body)))

(define s '(1 2 3 4 5))
(define (foldr f x i)
  (let ((s '()))
    (while (not (null x))
    (setq i (funcall f (car x) i))
    (setq x (cdr x)))
  i)
(foldr '+ s 0)
(foldr '* s 1)
(foldr 'cons (foldr 'cons s '())
       '(x y z w v))
